### ISSUE TITLE
modified ark-ff?

### ISSUE THREAD

**Issue by jakehemmerle** [mmagician/freivalds#1]
Are you using a modified `ark-ff`?

in `Cargo.toml`:

```ark-ff = { path = "/Users/marcin/personal/arkworks/algebra/ff" }```

You import Montgomery curves in `main.rs` but I don't see it in anywhere at https://docs.rs/ark-ff/0.3.0/ark_ff/index.html

**Comment by mmagician** [comment]
Actually no, it's just a local fork. The reason I didn't pull it from github instead, is that I can check definitions and impl of `ff` methods locally, and it's easier to browse. But it's the same version.
Thx for pointing it out.

And the version on crates.io is NOT the newest version. I normally recommend just using the one from github, would be:
`ark-ff = { git = "https://github.com/arkworks-rs/algebra" }`. This way you can get latest and greatest funcs from arkworks ;).

I'll update my Cargo later, thx!
